version: '3.9'

services:
  spring:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spring_app
    restart: always
    depends_on:
      - redis
    environment:
      - SERVER_PORT
      - SERVER_SESSION_COOKIE_HTTP_ONLY
      - SERVER_SESSION_COOKIE_SECURE
      - SERVER_SESSION_COOKIE_MAX_AGE
      - SERVER_SESSION_TIMEOUT
      - SPRING_DATA_REDIS_HOST
      - SPRING_DATA_REDIS_PORT
      - SPRING_DATASOURCE_URL
      - SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_PASSWORD
      - SPRING_JPA_SHOW_SQL
      - ALIYUN_OSS_ENDPOINT
      - ALIYUN_OSS_BUCKET_NAME
      - ALIYUN_OSS_ACCESS_KEY
      - ALIYUN_OSS_SECRET_KEY
      - ALIYUN_OSS_EXPIRATION_HOURS
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SESSION
      - SERVER_COMPRESSION_ENABLED
      - SERVER_COMPRESSION_MIN_RESPONSE_SIZE
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
        compress: "true"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_nginx
    restart: always
    ports:
      - "80:80"              # HTTP
      - "443:443"            # HTTPS
    volumes:
      - ./certs:/etc/nginx/certs  # 挂载证书目录到容器内
    depends_on:
      - spring
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  redis:
    image: redis:6.2
    container_name: redis_server
    restart: always
    volumes:
      - redis_data:/data

volumes:
  redis_data:
